services:
  - type: web
    name: signglaze
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: NOTIFICATION_EMAIL
        value: sg_tech9@rediffmail.com
